SELECT 
    CONSULTA_RELATORIO.SABOR
    , CONSULTA_RELATORIO.ANO
    , CONSULTA_RELATORIO.QUANTIDADE_TOTAL
    , ROUND((CONSULTA_RELATORIO.QUANTIDADE_TOTAL / CONSULTA_RELATORIO.QUANTIDADE_GERAL) * 100, 2) AS PERCENTUAL_PARTICIPACAO
FROM
    (SELECT
        TP.SABOR AS SABOR
        , EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO
        , SUM(IT.QUANTIDADE) AS QUANTIDADE_TOTAL
        , 
            (SELECT 
                TOTAL_ANO.QUANTIDADE_GERAL 
            FROM
                (SELECT
                    EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO
                    , SUM(INF.QUANTIDADE) AS QUANTIDADE_GERAL
                FROM
                    NOTAS_FISCAIS NF INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
                WHERE 
                    EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
                GROUP BY
                    EXTRACT(YEAR FROM NF.DATA_VENDA)
                ) TOTAL_ANO
            ) AS QUANTIDADE_GERAL
    FROM
        ITENS_NOTAS_FISCAIS IT 
        INNER JOIN TABELA_DE_PRODUTOS TP ON IT.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
        INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = IT.NUMERO
        WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
        GROUP BY TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
        ORDER BY QUANTIDADE_TOTAL DESC) 
    CONSULTA_RELATORIO;