SELECT * FROM TABELA_DE_CLIENTES;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE > 20;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE < 20;

SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE <> 18;

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '14/11/95';

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '14/11/1995';

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= TO_DATE('14/11/1995','DD/MM/YYYY');

SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= TO_DATE('11/14/1995','MM/DD/YYYY');

-- Com o Between é possível filtrar algo cujo valor está entre um e outro, incluindo o próprio limite informado
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE BETWEEN 17 AND 22;

-- O teste de > ou < usando textos, considera a ordem alfabética, por exemplo, A é menor e B, então André é menor que Bruno
SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO >= 'Lapa';
