SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF, NOME, BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

SELECT NOME, CPF, CIDADE, BAIRRO FROM TABELA_DE_CLIENTES;

-- Usando Alias nas colunas
SELECT CPF AS IDENTIFICADOR, NOME AS "NOME DE CLIENTE", BAIRRO, CIDADE FROM TABELA_DE_CLIENTES;

-- Usando Alias na tabela
SELECT CPF AS IDENTIFICADOR, NOME AS "NOME DE CLIENTE", TDC.BAIRRO, CIDADE FROM TABELA_DE_CLIENTES TDC;

-- Está buscando todos os campos da tabela representada pelo Alias TDC
SELECT TDC.* FROM TABELA_DE_CLIENTES TDC;

