SELECT * FROM ITENS_NOTAS_FISCAIS;
SELECT SABOR, TABELA_DE_PRODUTOS.* FROM TABELA_DE_PRODUTOS;


SELECT
    TP.SABOR AS SABORES,
    EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
    SUM(IT.QUANTIDADE) AS TOTAL_SABORES
FROM
    ITENS_NOTAS_FISCAIS IT
INNER JOIN
    TABELA_DE_PRODUTOS TP
ON IT.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
INNER JOIN
    NOTAS_FISCAIS NF
ON NF.NUMERO = IT.NUMERO
WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016
GROUP BY TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)
ORDER BY TOTAL_SABORES DESC;
